### PR TITLE
Ported Sqids to Nim

### PR DESCRIPTION
**Pull request by DavideGalilei**
- [x] Following the [official specification](https://github.com/sqids/sqids-spec)
- [x] Updated [blocklist](https://github.com/sqids/sqids-blocklist)
- [x] GitHub CI coverage
- [x] All tests passing

### CODE REVIEW

**Comment by 4kimov** [comment]
Hi @DavideGalilei,

Thank you for the PR! Very nice, invited you as a maintainer to this repo (feel free to push as needed). I take it this repo is ready to go and I can update the website to include Nim?

**Comment by DavideGalilei** [comment]
Hi @4kimov,
The repo should be ready to use. I just noticed, though, that while copying the README from the JavaScript repo I made some typos in the code examples. I'm fixing it right now.
By the way, to make `nimble install sqids` work (without the full GitHub url), it's possible to add the package to the nimble repository: https://github.com/nim-lang/packages#adding-your-own-package

**Comment by DavideGalilei** [comment]
I just sent a Pull Request to the Nimble packages repository: https://github.com/nim-lang/packages/pull/2762
Once it gets approved, I will update the installation instructions in the README.

**Comment by 4kimov** [comment]
Very nice, thank you. I'll update the website.

**Pull request merged**
